### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by buep** [Praqma/jenkins4casc#1]
##- [x] Bases on default Jenkins docker hub image
- [x] should not run startup guide with plugin installation and admin secrets
- [x] should handle plugin installation, for now using `install-plugins.sh`, later we will move to casc to handle it (#4)
- [ ] ~~~* *should* obviously install our Jenkins configuration as code plugin from most recent version publicly available in update center~~~ See #5

**Comment by buep** [comment]
Related to https://github.com/Praqma/praqma-jenkins-casc/issues/8

**Comment by MadsNielsen** [comment]
Ok, I've started work on this. I've setup autobuild for the this project on dockerhub. Autobuild is configured to build  the image with `latest` docker tag from commits on master. Git tags will be labelled with the same name as the tag. 

Suggest to follow the pattern: The tag will be the same as the version of the included Configuration as Code plugin. So for instance, the first version, when it's ready will be the full name `praqma/jenkins4casc:0.2-alpha`.

**Comment by buep** [comment]
>Suggest to follow the pattern: The tag will be the same as the version of the included Configuration as Code plugin. So for instance, the first version, when it's ready will be the full name praqma/jenkins4casc:0.2-alpha.

Fine, just write the release process and versijon strategi in the readme

**Comment by buep** [comment]
That's fine. Btw....im not too sure on https://github.com/Praqma/jenkins4casc/issues/1 the last point is for me not a good idea. Should our image not always select a specific version?


1 reply
bue.petersen [< 1 minute ago]
Yes, indeed, that is also what I mean... as in not referring to `latest` but a specific version  as you suggest.

For now it means we will need to update the version in the dockerfile by hand, but you can make a new issue for the backlog on automating the process, so when a new casc plugin is released, we automatically bump the version used in dockerfile, commit, push and build and test tit.

**Comment by MadsNielsen** [comment]
The last part of this issue is desribed in #5

**Comment by MadsNielsen** [comment]
Closing this. The remainder of this has been placed in #5
