### ISSUE TITLE
Configure autobuilds on docker hub

### ISSUE THREAD

**Issue by buep** [Praqma/jenkins4casc#3]
Should build latest, should build tagged versions and tag them with the version mentioned by the tag.

Describe our release process in the readme, saying we release version by tagging.

**Comment by buep** [comment]
Related to https://github.com/Praqma/praqma-jenkins-casc/issues/8

**Comment by MadsNielsen** [comment]
I managed to fix autobuild. Missing application integration: 
![hub](https://user-images.githubusercontent.com/1484793/38296152-beb1486c-37f0-11e8-9f35-65c83af541eb.png)
