### ISSUE TITLE
Move plugin installation to jenkins.yaml

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/jenkins4casc#4]
Once ready, we want to move the installation of plugins to the .yml file and the casc plugin.

Very simple once the process for plugins is in place

**Comment by buep** [comment]
Related to https://github.com/Praqma/praqma-jenkins-casc/issues/8

**Comment by MadsNielsen** [comment]
Blocked by: https://github.com/jenkinsci/configuration-as-code-plugin/pull/43

**Comment by buep** [comment]
Actually we just agreed this is not relevant, because the docker image here jenkins4casc needs to use plugins.txt to install casc plugin itself.

While we would expect our general demo setup to install plugins through casc plugin.
